### math/theory fundamentals of deep learning

In [7]:
import torch
import numpy as np
from typing import Tuple
import matplotlib.pyplot as plt

#### vector/tensor normalization

In [ ]:
v = np.array([1.1, 0.2, 0.3, 2.4, 0.2, 0.3, 1.7, 0.4, 0.5, 0.3, 0.8, 0.9])

# compute L2 norm
v_norm = v / np.linalg.norm(v)
print("L2 norm:", v_norm)

# check if normalized (allowing small numerical error)
if np.isclose(norm, 1.0, 0.1):
    print("Embedding is L2 normalized")
else:
    print("Embedding is NOT L2 normalized")

In [ ]:
norm = lambda v, p: sum([abs(x)**p for x in v])/p
euclideanNorm = lambda v: sum([abs(x)**2 for x in v])/2
l1Norm = lambda v: sum([abs(x) for x in v])
maxNorm = lambda v: max(v)

# norms basically measure the size of a vector, formally L^p
# f : V -> (x <= R^+)
# eucledian norm (L^2) is simply the euclidean distance from the origin
#   to the point identified by x

#### useful/important torch ops

In [10]:
# torch.arange(start=0, end, step=1)
torch.arange(5), torch.arange(4, 10), torch.arange(0, 3, 0.5)

(tensor([0, 1, 2, 3, 4]),
 tensor([4, 5, 6, 7, 8, 9]),
 tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000]))

In [32]:
# torch.empty()
torch.empty(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [16]:
# torch.randn(*size, *)
# rand numbers from a normal distribution with mean 0 and variance 1
torch.randn(5), torch.randn(2, 2)

(tensor([ 0.9701, -0.9327,  1.0902, -0.4303, -1.6986]),
 tensor([[ 0.6676, -2.2604],
         [ 0.1939, -0.4340]]))

In [19]:
# torch.outer(input, vec2, *)
# an outer product takes 2 vectors and produces a matrix (n x m) if input len is n and vec2 len is m
# think of it like you put input on the left vertically and vec2 at the top horizontally and then calc
#  the products of each combo of numbers at each matrix position (n_i x m_i)
torch.outer(
    torch.arange(1., 5.),
    torch.arange(1., 4.),
)

tensor([[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 4.,  8., 12.]])

In [20]:
# torch.broadcast_to(input, shape)
torch.broadcast_to(
    torch.tensor([1, 2, 3]),
    (3, 3)
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [22]:
# torch.polar(abs, angle, *)
# complex tensor whose elements are cartesian coords corresponding to the polar coords with abs and angle
torch.polar(
    torch.tensor([1, 2], dtype=torch.float64),
    torch.tensor([np.pi / 2, 5 * np.pi / 4], dtype=torch.float64),
)

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

In [23]:
# torch.full_like(input, fill_value)
# copies shape of input and copies fill_value to every pos
torch.full_like(
    torch.randn(2, 3),
    69,
)

tensor([[69., 69., 69.],
        [69., 69., 69.]])

In [30]:
# torch.bernoulli(input, *)
# get binary random numbers from bernouli dist where each val in input (0, 1) is the probablity of 0 or 1
torch.bernoulli(
    torch.empty(3, 3).uniform_(0, 1)
)

tensor([[0., 1., 0.],
        [0., 0., 0.],
        [1., 1., 1.]])

In [ ]:
# torch.topk

In [ ]:
# torch.combinations

In [71]:
# torch.Tensor.view(*shape)
# same data diff shape
x = torch.randn(2, 3)
x, x.view(3, 2)

(tensor([[ 0.0096, -0.2896,  0.5056],
         [-0.4422, -1.4588, -0.2258]]),
 tensor([[ 0.0096, -0.2896],
         [ 0.5056, -0.4422],
         [-1.4588, -0.2258]]))

In [ ]:
# torch.squeeze/unsqueeze

In [64]:
# torch.reshape
a = torch.arange(4.)
b = torch.tensor([[0, 1], [2, 3]])
a, b, torch.reshape(a, (2, 2)), torch.reshape(b, (-1,))

(tensor([0., 1., 2., 3.]),
 tensor([[0, 1],
         [2, 3]]),
 tensor([[0., 1.],
         [2., 3.]]),
 tensor([0, 1, 2, 3]))

In [53]:
# torch.where(condition, input)
torch.where(torch.randn(3, 2) > 0, 1.0, 0.0), torch.where(torch.randn(1, 3) > 0, 69.0, 420.0)

(tensor([[1., 0.],
         [0., 1.],
         [1., 0.]]),
 tensor([[420.,  69., 420.]]))

In [ ]:
# torch.trapz (trapezoid)

In [59]:
# torch.linspace(start, end, steps, *)
# 1d tensor of size steps whose values are evenly spaced from start to end inclusive
torch.linspace(3, 10, steps=5), torch.linspace(-10, 10, steps=5), torch.linspace(0, 10, steps=1)

(tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000]),
 tensor([-10.,  -5.,   0.,   5.,  10.]),
 tensor([0.]))