In [1]:
import torch

In [16]:
# shape shifting in pytorch
# https://www.paepper.com/blog/posts/shapeshifting-pytorch/

test = torch.tensor([1, 2, 3])
print(test.shape, test)

# need 2 dimensions?
test_batch = test.unsqueeze(0)
test_batch_equiv = test[None, :] # or [None]
print(test_batch, test_batch.shape)
print(test_batch_equiv, test_batch_equiv.shape)

# need to reduce dimensionality back to just 1 item?
print(test.unsqueeze(0).squeeze(0))

# squeeze without an input parameter will remove all dimensions of size 1

torch.Size([3]) tensor([1, 2, 3])
tensor([[1, 2, 3]]) torch.Size([1, 3])
tensor([[1, 2, 3]]) torch.Size([1, 3])
tensor([1, 2, 3])
